### ISSUE TITLE
大佬，求助：部署到vercel 出错

### ISSUE THREAD

**Issue by tiwentichat** [daodaolee/china-color#2]
大佬，想部署一个给妹子- -！
出现问题如下：<html>
<body>

npm ERR! code ENOTFOUND
--
18:43:13.794 | npm ERR! syscall getaddrinfo
18:43:13.795 | npm ERR! errno ENOTFOUND
18:43:13.797 | npm ERR! network request to http://artifactory.intra.xiaojukeji.com/artifactory/api/npm/npm/yorkie/-/yorkie-2.0.0.tgz?dl=https%3A%2F%2Fregistry.npmmirror.com%2Fyorkie%2F-%2Fyorkie-2.0.0.tgz failed, reason: getaddrinfo ENOTFOUND artifactory.intra.xiaojukeji.com
18:43:13.797 | npm ERR! network This is a problem related to network connectivity.
18:43:13.797 | npm ERR! network In most cases you are behind a proxy or have bad network settings.
18:43:13.797 | npm ERR! network
18:43:13.798 | npm ERR! network If you are behind a proxy, please make sure that the
18:43:13.798 | npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
18:43:13.825 |  
18:43:13.826 | npm ERR! A complete log of this run can be found in: /vercel/.npm/_logs/2023-12-01T10_41_16_161Z-debug-0.log
18:43:13.850 | Error: Command "npm install" exited with 1

</body>
</html>

这个好像要用到了xiaojukeji，不知道什么情况，大佬可以看一下不，感谢 - -！

**Comment by tiwentichat** [comment]
`
<html>
<body>

npm ERR! code ENOTFOUND
--
18:43:13.794 | npm ERR! syscall getaddrinfo
18:43:13.795 | npm ERR! errno ENOTFOUND
18:43:13.797 | npm ERR! network request to http://artifactory.intra.xiaojukeji.com/artifactory/api/npm/npm/yorkie/-/yorkie-2.0.0.tgz?dl=https%3A%2F%2Fregistry.npmmirror.com%2Fyorkie%2F-%2Fyorkie-2.0.0.tgz failed, reason: getaddrinfo ENOTFOUND artifactory.intra.xiaojukeji.com
18:43:13.797 | npm ERR! network This is a problem related to network connectivity.
18:43:13.797 | npm ERR! network In most cases you are behind a proxy or have bad network settings.
18:43:13.797 | npm ERR! network
18:43:13.798 | npm ERR! network If you are behind a proxy, please make sure that the
18:43:13.798 | npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
18:43:13.825 |  
18:43:13.826 | npm ERR! A complete log of this run can be found in: /vercel/.npm/_logs/2023-12-01T10_41_16_161Z-debug-0.log
18:43:13.850 | Error: Command "npm install" exited with 1


</body>
</html>
`

上面显示是乱的，我重新发一下

**Comment by tiwentichat** [comment]
额。。。代码块失灵了吗 - -！

**Comment by daodaolee** [comment]
把lock文件删掉，再部署一次

**Comment by daodaolee** [comment]
你也可以用这个仓库，重构了一点东西 [china-color-refactor](https://github.com/daodaolee/china-color-refactor) @tiwentichat

**Comment by tiwentichat** [comment]
> 你也可以用这个仓库，重构了一点东西 [china-color-refactor](https://github.com/daodaolee/china-color-refactor) @tiwentichat
好的，感谢大佬！我去试试

**Comment by tiwentichat** [comment]
> 你也可以用这个仓库，重构了一点东西 [china-color-refactor](https://github.com/daodaolee/china-color-refactor) @tiwentichat

大佬，出状况了：
1，china color refactor 这个项目成功部署了，但是显示的category 都是和黄白游的一样，全部都是显示立春。如果改成把这个地方的立春改成其他内容，或者直接删除，整个页面也都会变成其他内容或者不显示。

和第二第三条的category无关，也修改然后重新部署，没有影响。

2，本项目（china color）删除了lock，新的提示：<html>
<body>



error @achrinza/node-ipc@9.2.2: The engine "node" is incompatible with this module. Expected version "8 \|\| 10 \|\| 12 \|\| 14 \|\| 16 \|\| 17". Got "18.17.1"
11:32:15.907 | error Found incompatible module.
11:32:15.907 | info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
11:32:15.970 | Error: Command "yarn install" exited with 1
11:32:16.305

<br class="Apple-interchange-newline">
</body>
</html>

**Comment by daodaolee** [comment]
@tiwentichat node版本太高了，建议你fork一份，自己跑通了再部署，应该配置上不会有什么太大的问题。refactor那一份，我是自己跑通了然后没部署，你可以自己试一下，整体的代码挺简单的。

**Comment by tiwentichat** [comment]
> @tiwentichat node版本太高了，建议你fork一份，自己跑通了再部署，应该配置上不会有什么太大的问题。refactor那一份，我是自己跑通了然后没部署，你可以自己试一下，整体的代码挺简单的。

好的，我看一下，感谢大佬回复！
